version: '3.5'

services:
  app:
    container_name: SpringBoot_Helloworld
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: "Asia/Tokyo"
      SELF_PORT: ${APP_TARGET_PORT}
      SELF_IP: 0.0.0.0
      MYSQL_SERVER_HOST_NAME: ${DATABASE_SERVER_HOST_NAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - "${APP_TARGET_PORT}:8080"
    tty: true
    networks:
      - springboot-network
    depends_on:
      - database
    restart: always

  database:
    container_name: ${DATABASE_SERVER_HOST_NAME}
    build:
      context: ./mysql_server
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_SERVER_HOST_NAME: ${DATABASE_SERVER_HOST_NAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    tty: true
    networks:
      - springboot-network
    restart: always

networks:
  springboot-network:
    driver: bridge
