version: '3.5'

services:
  app:
    container_name: SpringBoot_Helloworld
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SELF_PORT: ${APP_TARGET_PORT}
      SELF_IP: 0.0.0.0
      DATABASE_HOST: ${DATABASE_SERVER_HOST_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWD: ${DATABASE_USER_PASSWORD}
    ports:
      - "${APP_TARGET_PORT}:8080"
    restart: always

  database:
    container_name: ${DATABASE_SERVER_HOST_NAME}
    build:
      context: ./mysql_server
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${DATABASE_SERVER_HOST_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    restart: always

